version: '3'
services:
  db:
    image: postgres:14-alpine
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: nestjs_container
    restart: always
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USERNAME: test
      DB_PASSWORD: test
      DB_DATABASE: test_db
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    command: npm run start:dev

volumes:
  db_data:
